CREATE USER pb_analyst WITH PASSWORD '..pwd...';

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO pb_analyst;

GRANT CONNECT ON DATABASE "mps-db" TO pb_analyst;
GRANT USAGE ON SCHEMA public TO pb_analyst;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pb_analyst;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO pb_analyst;